apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ztunnel-monitor
  namespace: ztunnel
spec:
  targetLabels:
    - app
  selector:
    matchLabels:
      service: ztunnel
  endpoints:
    - port: http-monitoring
      interval: 30s
