apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"ServiceEntry","metadata":{"annotations":{},"name":"cnn","namespace":"bookinfo"},"spec":{"hosts":["edition.cnn.com"],"location":"MESH_EXTERNAL","ports":[{"name":"http-port","number":80,"protocol":"HTTP"},{"name":"https","number":443,"protocol":"HTTPS"}],"resolution":"DNS"}}
  creationTimestamp: "2025-03-27T21:09:25Z"
  generation: 2
  name: cnn
  namespace: bookinfo
  resourceVersion: "140886"
  uid: 79a5ecab-852b-4355-9439-0da709842cc9
spec:
  hosts:
  - edition.cnn.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
