
# DO NOT install this if one intend to use OTEL
----
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: enable-prometheus-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
