apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: rh-docs
  namespace: curl
spec:
  hosts:
    - docs.redhat.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
