apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-for-docs-redhat-com
spec:
  host: docs.redhat.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 80
