kind: Istio
apiVersion: sailoperator.io/v1
metadata:
  name: default
spec:
  namespace: istio-system
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  values:
    meshConfig:
      enableTracing: true
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: otel-collector.istio-system.svc.cluster.local
  version: v1.26.3
