apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
  resourceVersion: "286545"
  name: kiali
  namespace: istio-system
  istio_namespace: istio-system
  version: default
spec:
  deployment:
    logger:
      log_level: info
    view_only_mode: false
  external_services:
    grafana:
      enabled: true
      external_url: "https://grafana-istio-system.apps.cluster-xjbz7.xjbz7.sandbox478.opentlc.com"
      internal_url: "http://grafana.istio-system.svc.cluster.local:3000"
    tracing:
      enabled: true
      namespace_selector: true
      tempo_config:
        datasource_uid: aercfifi24lj4c
        org_id: "1"
        url_format: jaeger
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        insecure_skip_verify: false
        type: bearer
        use_kiali_token: true
      query_timeout: 15
      internal_url: "https://tempo-sample-gateway.tempo.svc.cluster.local:8081/api/traces/v1/north/tempo"
      provider: tempo
      health_check_url: "https://tempo-sample-gateway.tempo.svc.cluster.local:8080/api/traces/v1/north/tempo/api/echo"
      use_grpc: false
      external_url: "https://tempo-sample-gateway-tempo.apps.cluster-xjbz7.xjbz7.sandbox478.opentlc.com/api/traces/v1/north/search"
  istio_namespace: istio-system
  version: default
