apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  annotations:
  name: otel
  namespace: istio-system
spec:
  config:
    exporters:
      otlp:
        auth:
          authenticator: bearertokenauth
        endpoint: tempo-sample-gateway.tempo.svc.cluster.local:8090
        headers:
          X-Scope-OrgID: north
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          insecure: false
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
        - bearertokenauth
      pipelines:
        traces:
          exporters:
            - otlp
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  managementState: managed
  upgradeStrategy: automatic
