kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
  namespace: istio-system
spec:
  config:
    exporters:
      otlp:
        endpoint: tempo-sample-distributor.tempo.svc.cluster.local:4317
        tls:
          insecure: true
        headers:
          X-Scope-OrgID: "north"
    extensions:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http: {}
    service:
      pipelines:
        traces:
          exporters:
            - otlp
          receivers:
            - otlp
