apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
    labels:
      k8s-app: istio-proxies
    name: istio-proxies-monitor
    namespace: istio-system
  spec:
    endpoints:
    - interval: 30s
      path: /stats/prometheus
      port: grpc-envoy-prom
    namespaceSelector:
      any: true
    selector:
      matchExpressions:
      - key: security.istio.io/tlsMode
        operator: Exists
kind: List
metadata:
  resourceVersion: ""
