#!/usr/bin/env bash
set -Eeuo pipefail

#
# Create an ODF/NooBaa S3 bucket for Tempo and the Tempo storage Secret.
#
# Usage:
#   ./create_tempo_odf_bucket.sh <namespace>
#
# Example:
#   ./create_tempo_odf_bucket.sh tempo
#
# Result for namespace "tempo":
#   Kubernetes namespace: tempo
#   S3 bucket name:       tempo
#   OBC name:             tempo-obc
#   OBC Secret:           tempo-obc       (generated by ODF)
#   OBC ConfigMap:        tempo-obc       (generated by ODF)
#   Tempo Secret:         tempo-s3
#

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <namespace>" >&2
    exit 2
fi

NAMESPACE="$1"

STORAGE_CLASS="${STORAGE_CLASS:-openshift-storage.noobaa.io}"
OBC_NAME="${OBC_NAME:-${NAMESPACE}-obc}"
TEMPO_SECRET_NAME="${TEMPO_SECRET_NAME:-tempo-s3}"
BOUND_TIMEOUT_SECONDS="${BOUND_TIMEOUT_SECONDS:-300}"

for cmd in oc base64; do
    command -v "${cmd}" >/dev/null 2>&1 || {
        echo "ERROR: required command not found: ${cmd}" >&2
        exit 2
    }
done

#
# Kubernetes namespace names are valid DNS labels and are also suitable for
# the intended simple S3 bucket naming convention here.
#
if [[ ! "${NAMESPACE}" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]]; then
    echo "ERROR: invalid namespace/bucket name: ${NAMESPACE}" >&2
    echo "Use lowercase letters, digits, or '-'; start/end with alphanumeric." >&2
    exit 2
fi

if (( ${#NAMESPACE} < 3 || ${#NAMESPACE} > 63 )); then
    echo "ERROR: namespace/bucket name must be 3..63 characters for S3 compatibility." >&2
    exit 2
fi

echo "Tempo ODF bucket provisioning"
echo "  namespace     = ${NAMESPACE}"
echo "  bucket        = ${NAMESPACE}"
echo "  OBC           = ${OBC_NAME}"
echo "  storage class = ${STORAGE_CLASS}"
echo "  Tempo secret  = ${TEMPO_SECRET_NAME}"
echo

#
# Namespace must exist because both the OBC and TempoStack credentials belong
# to the application namespace.
#
if ! oc get namespace "${NAMESPACE}" >/dev/null 2>&1; then
    echo "Creating namespace ${NAMESPACE} ..."
    oc create namespace "${NAMESPACE}"
fi

#
# Verify the requested StorageClass before creating the claim.
#
if ! oc get storageclass "${STORAGE_CLASS}" >/dev/null 2>&1; then
    echo "ERROR: StorageClass not found: ${STORAGE_CLASS}" >&2
    exit 1
fi

#
# Protect against accidentally adopting an unrelated pre-existing OBC.
#
if oc get objectbucketclaim.objectbucket.io \
      "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      >/dev/null 2>&1; then

    existing_bucket="$(
        oc get objectbucketclaim.objectbucket.io \
          "${OBC_NAME}" \
          -n "${NAMESPACE}" \
          -o jsonpath='{.spec.bucketName}'
    )"

    existing_sc="$(
        oc get objectbucketclaim.objectbucket.io \
          "${OBC_NAME}" \
          -n "${NAMESPACE}" \
          -o jsonpath='{.spec.storageClassName}'
    )"

    if [[ "${existing_bucket}" != "${NAMESPACE}" ]]; then
        echo "ERROR: existing OBC ${NAMESPACE}/${OBC_NAME} points to bucket '${existing_bucket}'," >&2
        echo "       but this script requires bucket '${NAMESPACE}'." >&2
        exit 1
    fi

    if [[ "${existing_sc}" != "${STORAGE_CLASS}" ]]; then
        echo "ERROR: existing OBC ${NAMESPACE}/${OBC_NAME} uses StorageClass '${existing_sc}'," >&2
        echo "       expected '${STORAGE_CLASS}'." >&2
        exit 1
    fi

    echo "OBC already exists and matches requested configuration."
else
    echo "Creating ObjectBucketClaim ${NAMESPACE}/${OBC_NAME} ..."

    oc apply -f - <<EOF
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ${OBC_NAME}
  namespace: ${NAMESPACE}
spec:
  bucketName: ${NAMESPACE}
  storageClassName: ${STORAGE_CLASS}
EOF
fi

#
# Wait explicitly for successful provisioning.
#
echo "Waiting for OBC to become Bound ..."

deadline=$((SECONDS + BOUND_TIMEOUT_SECONDS))

while true; do
    phase="$(
        oc get objectbucketclaim.objectbucket.io \
          "${OBC_NAME}" \
          -n "${NAMESPACE}" \
          -o jsonpath='{.status.phase}' \
          2>/dev/null || true
    )"

    case "${phase}" in
        Bound)
            echo "OBC is Bound."
            break
            ;;
        Failed)
            echo "ERROR: OBC provisioning failed." >&2
            oc describe objectbucketclaim.objectbucket.io \
              "${OBC_NAME}" \
              -n "${NAMESPACE}" >&2 || true
            exit 1
            ;;
    esac

    if (( SECONDS >= deadline )); then
        echo "ERROR: timed out after ${BOUND_TIMEOUT_SECONDS}s waiting for OBC to become Bound." >&2
        oc describe objectbucketclaim.objectbucket.io \
          "${OBC_NAME}" \
          -n "${NAMESPACE}" >&2 || true
        exit 1
    fi

    sleep 2
done

#
# ODF creates a Secret and ConfigMap with the same name as the OBC, in the
# same namespace. Wait for both to exist before reading credentials.
#
echo "Waiting for OBC Secret and ConfigMap ..."

deadline=$((SECONDS + 60))
while true; do
    if oc get secret "${OBC_NAME}" -n "${NAMESPACE}" >/dev/null 2>&1 &&
       oc get configmap "${OBC_NAME}" -n "${NAMESPACE}" >/dev/null 2>&1; then
        break
    fi

    if (( SECONDS >= deadline )); then
        echo "ERROR: OBC is Bound but generated Secret/ConfigMap did not appear." >&2
        exit 1
    fi

    sleep 1
done

bucket="$(
    oc get configmap "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      -o jsonpath='{.data.BUCKET_NAME}'
)"

bucket_host="$(
    oc get configmap "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      -o jsonpath='{.data.BUCKET_HOST}'
)"

bucket_port="$(
    oc get configmap "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      -o jsonpath='{.data.BUCKET_PORT}'
)"

access_key_id="$(
    oc get secret "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' |
    base64 --decode
)"

access_key_secret="$(
    oc get secret "${OBC_NAME}" \
      -n "${NAMESPACE}" \
      -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' |
    base64 --decode
)"

for value_name in bucket bucket_host bucket_port access_key_id access_key_secret; do
    if [[ -z "${!value_name}" ]]; then
        echo "ERROR: ${value_name} was not returned by the OBC." >&2
        exit 1
    fi
done

#
# This script requested an exact bucket name. Refuse to continue if the
# provisioner returned something different.
#
if [[ "${bucket}" != "${NAMESPACE}" ]]; then
    echo "ERROR: ODF returned bucket '${bucket}', expected '${NAMESPACE}'." >&2
    exit 1
fi

#
# NooBaa/ODF S3 endpoint is normally HTTPS.
#
if [[ "${bucket_port}" == "443" ]]; then
    endpoint="https://${bucket_host}"
else
    endpoint="https://${bucket_host}:${bucket_port}"
fi

#
# Create/update the Secret expected by TempoStack.
#
# The OBC-generated Secret is intentionally NOT reused directly because its
# key names differ from the Tempo Operator's S3 storage Secret contract.
#
echo "Creating Tempo storage Secret ${NAMESPACE}/${TEMPO_SECRET_NAME} ..."

oc create secret generic "${TEMPO_SECRET_NAME}" \
    -n "${NAMESPACE}" \
    --from-literal=bucket="${bucket}" \
    --from-literal=endpoint="${endpoint}" \
    --from-literal=access_key_id="${access_key_id}" \
    --from-literal=access_key_secret="${access_key_secret}" \
    --dry-run=client \
    -o yaml |
oc apply -f -

echo
echo "Success."
echo "  namespace      = ${NAMESPACE}"
echo "  bucket         = ${bucket}"
echo "  OBC            = ${OBC_NAME}"
echo "  endpoint       = ${endpoint}"
echo "  Tempo secret   = ${TEMPO_SECRET_NAME}"
echo
echo "TempoStack storage reference:"
cat <<EOF
spec:
  storage:
    secret:
      name: ${TEMPO_SECRET_NAME}
      type: s3
EOF
