apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-gw
  namespace: curl
spec:
  selector:
    matchLabels:
      istio: egress-gw
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        istio: egress-gw
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: istio-proxy
          image: auto
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-pro
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      serviceAccountName: secret-reader
