apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxies-monitor
  namespace: bookinfo
spec:
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: http-envoy-prom
    scheme: http
  selector:
    matchLabels:
      app: istio-proxy-metrics
